services:
  sonarqube:
    image: sonarqube:community # 소나큐브 커뮤니티 버전 이미지를 활용
    depends_on:
      - sonar_db # sonar_db라는 이름의 service 식별자에 의존, 해당 의존성을 가진 이미지 기반의 컨테이너가 먼저 실행 되어야 함
    environment: # DB 연결 설정 정보
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes: # SQ 서버에서 볼륨을 통해 실행과정에서 발생하는 데이터들을 관리,저장할 디렉토리 경로
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  sonar_db: # SQ 서버가 활용할 DBMS 설정
    image: postgres:16
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db:/var/lib/postgresql
      - sonar_db_data:/var/lib/postgresql/data

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:
