spring:
  application:
    # MSA에서는 이름으로 각 마이크로서비스들의 이름을 식별
    name: eureka-server

server:
  # Eureka 서버의 기본 포트 번호
  port: 8761

eureka:
  client:
    # Eureka 서버가 자기 자신을 레지스트리에 등록하지 않도록
    register-with-eureka: false
    # 다른 Eureka 서버에 등록하지 않도록
    fetch-registry: false
