spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/msa_step02_payment?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

# 실패 유발 시나리오용 랜덤값 설정
simulation:
  payment:
    success-rate: 70  # 0-100 퍼센트

server:
  port: 8081
