server:
  port:8888

spring:
  application:
    name: config-server

    cloud:
      #cloud-config ?? ?? ??
      config:
        # ?? ??? ??? ??? ?? ??
        server:
          #?? ??? git?? ?????
          git:
            # Git ??? ??
            uri: https://github.com/microness/config-repo
            # ?? ??? ??,
            default-label: main
            #Git ??? ?? ? ???? ??(?)
            timeout: 5